import type { Metadata } from "next";
import Link from "next/link";
import DocsBreadcrumb from "@/components/docs/DocsBreadcrumb";
import DocsPrevNext from "@/components/docs/DocsPrevNext";
import DocsCallout from "@/components/docs/DocsCallout";

export const metadata: Metadata = {
  title: "Research & Background",
  description: "Research methodology, mechanistic interpretability, and theoretical foundations of TokenPrint.",
};

export default function ResearchDocsPage() {
  return (
    <>
      <DocsBreadcrumb slug="research" title="Research & Background" />

      <p className="docs-meta">GETTING STARTED</p>
      <h1>Research &amp; Theoretical Background</h1>
      <p className="docs-intro">
        TokenPrint is grounded in research on transformer mechanistic interpretability, real-time activation tracing, and high-dimensional tensor trajectory visualization.
      </p>

      {/* Hero Diagram */}
      <div className="docs-image-frame">
        <svg width="100%" height="160" viewBox="0 0 680 160" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="0.5" y="0.5" width="679" height="159" rx="7.5" fill="#0A0B0D" stroke="#202225" />
          <line x1="40" y1="40" x2="640" y2="40" stroke="#141518" strokeDasharray="4 4" />
          <line x1="40" y1="80" x2="640" y2="80" stroke="#141518" strokeDasharray="4 4" />
          <line x1="40" y1="120" x2="640" y2="120" stroke="#141518" strokeDasharray="4 4" />
          
          <circle cx="100" cy="80" r="24" fill="#141518" stroke="#4C86FF" strokeWidth="1.5" />
          <text x="100" y="84" fill="#F5F5F5" fontSize="10" fontFamily="monospace" textAnchor="middle">Input X</text>

          <path d="M 124 80 Q 200 40 280 80 T 440 80 T 580 80" fill="none" stroke="#383A40" strokeWidth="1.5" strokeDasharray="3 3" />

          <rect x="230" y="60" width="100" height="40" rx="6" fill="#141518" stroke="#F5F5F5" strokeWidth="1.5" />
          <text x="280" y="84" fill="#F5F5F5" fontSize="11" fontFamily="monospace" textAnchor="middle">Residual Stream</text>

          <rect x="410" y="60" width="110" height="40" rx="6" fill="#141518" stroke="#383A40" />
          <text x="465" y="84" fill="#F5F5F5" fontSize="11" fontFamily="monospace" textAnchor="middle">Attention &amp; MLP</text>

          <circle cx="580" cy="80" r="24" fill="#141518" stroke="#10B981" strokeWidth="1.5" />
          <text x="580" y="84" fill="#F5F5F5" fontSize="10" fontFamily="monospace" textAnchor="middle">Logits</text>
        </svg>
        <p className="docs-image-caption">
          Conceptual diagram of residual stream propagation and activation flow across transformer layers.
        </p>
      </div>

      <hr />

      <h2 id="mechanistic-interpretability">Mechanistic Interpretability</h2>
      <p>
        Mechanistic interpretability aims to reverse-engineer trained neural networks into human-understandable algorithms. TokenPrint enables fine-grained inspection of model internals during execution by capturing exact activation values, attention scores, and projection weights without approximations.
      </p>

      <DocsCallout variant="tip" title="Zero-Mock Guarantee">
        Every tensor value, norm, matrix heat map, and activation vector shown in TokenPrint is derived directly from live forward pass telemetry generated by standard model execution backends.
      </DocsCallout>

      <hr />

      <h2 id="core-research-pillars">Core Research Pillars</h2>
      
      <h3>1. Residual Stream Telemetry</h3>
      <p>
        The residual stream serves as the central communication bus of the transformer architecture. TokenPrint visualizes how hidden state representations evolve layer-by-layer as attention heads and MLP blocks write information into the stream.
      </p>

      <h3>2. Grouped Query Attention &amp; Key-Value Cache</h3>
      <p>
        Modern open LLMs (such as Qwen2.5, LLaMA-3, and Mistral) utilize Grouped Query Attention (GQA) to minimize KV cache footprint during decoding. TokenPrint provides explicit visual breakdowns of Query head to Key/Value head assignments, head-wise entropy, and memory allocation.
      </p>

      <h3>3. High-Dimensional Spatial Projections</h3>
      <p>
        To render hidden state vectors in 3D, TokenPrint employs real-time dimensionality reduction techniques (including PCA and t-SNE projections) allowing researchers to observe vector trajectories across network depth.
      </p>

      <hr />

      <h2 id="references--literature">Key References &amp; Literature</h2>
      <p>
        TokenPrint builds upon foundational research in transformer architectures and interpretability:
      </p>

      <ul>
        <li>
          <strong>Attention Is All You Need</strong> (Vaswani et al., 2017) — <a href="https://arxiv.org/abs/1706.03762" target="_blank" rel="noopener noreferrer">arXiv:1706.03762</a>
        </li>
        <li>
          <strong>GQA: Training Generalized Multi-Query Transformer Models</strong> (Ainslie et al., 2023) — <a href="https://arxiv.org/abs/2305.13245" target="_blank" rel="noopener noreferrer">arXiv:2305.13245</a>
        </li>
        <li>
          <strong>RoFormer: Enhanced Transformer with Rotary Position Embedding</strong> (Su et al., 2021) — <a href="https://arxiv.org/abs/2104.09864" target="_blank" rel="noopener noreferrer">arXiv:2104.09864</a>
        </li>
        <li>
          <strong>SwiGLU: GLU Variants Improve Transformer</strong> (Shazeer, 2020) — <a href="https://arxiv.org/abs/2002.05202" target="_blank" rel="noopener noreferrer">arXiv:2002.05202</a>
        </li>
        <li>
          <strong>Transformer Circuits Framework</strong> (Elhage et al., Anthropic Research) — Mathematical framework for analyzing transformer activations.
        </li>
      </ul>

      <hr />

      <h2 id="citing-tokenprint">Citing TokenPrint</h2>
      <p>
        If you use TokenPrint in your research or technical work, please cite the repository:
      </p>

      <div className="docs-code-block">
        <div className="docs-code-header">
          <span className="docs-code-lang">bibtex</span>
        </div>
        <pre className="docs-code-pre">
          <code>{`@misc{tokenprint2026,
  author = {Selvaraj, Sudharsan},
  title = {TokenPrint: Interactive 3D Visual Debugger for LLM & Transformer Internals},
  year = {2026},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\\url{https://github.com/Sudharsanselvaraj/Token-Print}}
}`}</code>
        </pre>
      </div>

      <DocsPrevNext slug="research" />
    </>
  );
}
